// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Domain struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Ar    *int   `json:"ar"`
	Level *int   `json:"level"`
}

type DomainCategory struct {
	Name      string    `json:"name"`
	Domains   []*Domain `json:"domains"`
	Artifacts []*string `json:"artifacts"`
}
